# Generated by Django 5.0 on 2023-12-23 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('zip', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200, null=True)),
                ('certificate', models.FileField(null=True, upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('street', models.CharField(max_length=500, null=True)),
                ('city', models.CharField(max_length=500, null=True)),
                ('state', models.CharField(max_length=500, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('phone_no', models.CharField(max_length=10, null=True)),
                ('type_of_industry', models.CharField(max_length=500, null=True)),
                ('number_of_employee', models.CharField(max_length=500, null=True)),
                ('website', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=15, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='J_Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=200, null=True)),
                ('experience', models.CharField(choices=[('0 to 0 Months', '0 to 0 months'), ('0 to 6 Months', '0 to 6 months'), ('1 to 2 Years', '1 to 2 years'), ('more then 2 years', 'More Then 2 Years')], max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='<br><b>Enter company logo!!<b>', null=True, upload_to='')),
                ('c_name', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=3000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('expiry', models.DateField(null=True)),
                ('salary', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(max_length=40, null=True, unique=True)),
                ('type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=200)),
                ('status', models.CharField(choices=[('not_ok', 'not_ok'), ('ok', 'ok')], default='not_ok', max_length=50)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.author')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company_registration')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.location')),
                ('skills', models.ManyToManyField(to='app.skills')),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('company_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company_registration')),
            ],
        ),
        migrations.CreateModel(
            name='PG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_education', models.CharField(max_length=100, null=True)),
                ('institude', models.CharField(max_length=200, null=True)),
                ('university', models.CharField(max_length=100, null=True)),
                ('course', models.CharField(max_length=100, null=True)),
                ('specialization', models.CharField(max_length=100, null=True)),
                ('course_type', models.CharField(choices=[('FULL TIME', 'full time'), ('PART TIME', 'part time'), ('CORRESPONDANCE/DISTANCE LEARNING', 'correspondance/distance learning')], max_length=200, null=True)),
                ('course_duration_from', models.IntegerField(null=True)),
                ('course_duration_to', models.IntegerField(null=True)),
                ('CGPA_pg', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=20)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('objectives', models.CharField(max_length=200, null=True)),
                ('Resume', models.FileField(null=True, upload_to='')),
                ('experience', models.CharField(choices=[('Fresher', 'fresher'), ('0 to 6 Months', '0 to 6 months'), ('1 to 2 Years', '1 to 2 years'), ('more then 2 years', 'More Then 2 Years')], default='fresher', max_length=50, null=True)),
                ('type', models.CharField(max_length=15)),
                ('PG', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pg')),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.address')),
                ('certification', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.certification')),
                ('skill', models.ManyToManyField(to='app.j_skill')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='', max_length=200)),
                ('resume', models.FileField(null=True, upload_to='download')),
                ('apply_date', models.DateField(null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobpost')),
                ('jobtitle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.jobtitle')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200, null=True)),
                ('domain', models.CharField(max_length=200, null=True)),
                ('skills_and_tools', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.projects'),
        ),
        migrations.CreateModel(
            name='Ten_th',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_education', models.CharField(max_length=10, null=True)),
                ('Board', models.CharField(max_length=20, null=True)),
                ('passing_out_year', models.IntegerField(null=True)),
                ('school_medium', models.CharField(max_length=50, null=True)),
                ('total_mark_ten', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='Ten_th',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ten_th'),
        ),
        migrations.CreateModel(
            name='Twelve_th',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twelve_education', models.CharField(max_length=10, null=True)),
                ('Board', models.CharField(max_length=200, null=True)),
                ('passing_out_year', models.IntegerField(null=True)),
                ('school_medium', models.CharField(max_length=50, null=True)),
                ('total_mark_twelve', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='Twelve_th',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.twelve_th'),
        ),
        migrations.CreateModel(
            name='UG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ug_education', models.CharField(max_length=100, null=True)),
                ('institude', models.CharField(max_length=200, null=True)),
                ('university', models.CharField(max_length=100, null=True)),
                ('course', models.CharField(max_length=100, null=True)),
                ('specialization', models.CharField(max_length=100, null=True)),
                ('course_type', models.CharField(choices=[('FULL TIME', 'full time'), ('PART TIME', 'part time'), ('CORRESPONDANCE/DISTANCE LEARNING', 'correspondance/distance learning')], max_length=200, null=True)),
                ('course_duration_from', models.IntegerField(null=True)),
                ('course_duration_to', models.IntegerField(null=True)),
                ('CGPA_ug', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='uG',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ug'),
        ),
    ]
