# Generated by Django 5.0 on 2023-12-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jobtitle_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitle',
            name='expiry',
            field=models.DateField(null=True),
        ),
    ]
