# Generated by Django 5.0 on 2023-12-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_jobtitle_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='roll',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('closed', 'CLOSED')], default='active', max_length=20),
        ),
    ]
