# Generated by Django 5.0 on 2023-12-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_jobpost_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='roll',
            field=models.CharField(choices=[('active', 'active'), ('closed', 'closed')], default='active', max_length=20),
        ),
    ]
