# Generated by Django 5.0 on 2023-12-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_jobpost_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='roll',
            field=models.CharField(choices=[('not_ok', 'not_ok'), ('ok', 'ok')], default='not_ok', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('closed', 'closed')], default='active', max_length=20),
        ),
    ]
