# Generated by Django 5.0 on 2023-12-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_jobpost_roll_alter_jobpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(help_text='<br><b>upload your profile picture!!<b>', null=True, upload_to=''),
        ),
    ]
